---
title: "Code to Content"
subtitle: "The Art and Impact of Data Blogging"
author: "[Randi Bolt](https://www.rbolt.me/)"
date: "2/6/24"
format:
  revealjs:
    incremental: true 
title-slide-attributes:
    data-background-color: "beige"
---

## Agenda {background-color="beige"}

1. **Adventure Awaits**

    Reasons to Embark on Your Expedition

2. **Blogging Blueprint**

    Building Your Narrative With Quarto

3. **Curated Counsel**

    Advice for Smooth Sailing
    
4. **Dive Deeper**

    Resourcesful Links

# Adventure Awaits {background-color="beige"}

## Reasons to Embark on Your Expedition {background-color="beige"}

- Joy in Expression

- Own Your Narrative

- Continuous Growth and Learning

- Self Discovery 

- Reveal Fresh Perspectives

- Data Advocacy and Empowerment

- Embedded in R Culture

# Blogging Blueprint {background-color="beige"}

## Building Your Narrative With Quarto {background-color="beige"}

i. Familiarize Yourself with the Quarto Documentation 
    
:::: {.columns}

::: {.column width="50%"}

1. Generate Ideas

2. Seek Inspiration 

3. Plan Layout

4. Set the Groundwork

5. Link Your Work (Github)

6. Elevate your Reach (Netlify)

:::

::: {.column width="50%"}

7. Style (.scss)

8. Customize (.yaml)

9. Craft Engaging Landing page

10. Design Remaining Pages 

11. First Blog Post

12. Claim Your Domain

:::

::::

13. Track Your Impact (Google Analytics)

# Curated Council {background-color="beige"}

## Advice for Smooth Sailing {background-color="beige"}

- Consider Your Audience 

- Intentional Landing Page

- Avoid Duplicating Other Profiles

- Select the Right Tool for the Job

- Edit! Edit! Edit!

- Prioritize Accessibility

# Dive Deeper {background-color="beige"}

## Resourcesful Links {background-color="beige"}

- [Quarto > Websites > Creating a Blog](https://quarto.org/docs/websites/website-blog.html)

- [Creating a blog with Quarto in 10 steps](https://beamilz.com/posts/2022-06-05-creating-a-blog-with-quarto/en/)
    
    Bea Milz - [Blog](https://beamilz.com/) ([Repo](https://github.com/beatrizmilz/blog-en))

- [Create Your Data Science Portfolio with Quarto](https://www.youtube.com/watch?v=xtSFXtDf4cM) 

    Deepsha Menghani - [Blog](https://deepshamenghani.quarto.pub/dmenghani/) ([Repo](https://github.com/deepshamenghani/Portfolio_DeepshaM))

- [Style Your Quarto Blog without Knowing a lot of HTML/CSS](https://www.youtube.com/watch?v=ErRX8plZpQE) 

    Albert Rapp - [Blog](https://albert-rapp.de/)
    
- [Quarto/RMarkdown - What's Difference?](https://www.youtube.com/watch?v=i6rajzMkpD0)

    Ted Laderas - [Blog](https://laderast.github.io/) ([Repo](https://github.com/laderast/laderast.github.io))
